name: Tune

on:
  push:
    branches:
      - tune

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: make
        run: cd src && make clean && make -j build COMP=clang ARCH=x86-64-bmi2 EXE=x86-64-bmi2 && strip x86-64-bmi2

      - name: upload to fishtest
        run: curl https://test.pikafish.org/api/pre_upload -F file=@src/x86-64-bmi2 -F "file_type=engine" -F "password=${{ secrets.NOTHING }}"

      - name: print variables table
        run: printf 'quit' | src/x86-64-bmi2